# Generated by Django 5.0.6 on 2024-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
